# Generated by Django 4.2.1 on 2023-05-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbank', '0002_remove_cliente_nomefantasia_cliente_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='foto',
        ),
        migrations.AddField(
            model_name='cliente',
            name='celular',
            field=models.CharField(default='', max_length=20),
        ),
    ]
