# Generated by Django 4.2.1 on 2023-05-31 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='operacao',
            field=models.CharField(choices=[('PI', 'PIX'), ('DC', 'DOC'), ('NOM', 'NOME')], default='PI', max_length=3),
        ),
    ]
