# Generated by Django 4.2.1 on 2023-05-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='valorComJuros',
            new_name='valorParcelaJuros',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='valorTotalJuros',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
