# Generated by Django 4.2.1 on 2023-05-31 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashbank', '0002_alter_movimentacao_operacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimentacao',
            old_name='cliente',
            new_name='fk_movimentacao',
        ),
    ]
