# Generated by Django 4.2.1 on 2023-05-18 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashbank', '0006_alter_cliente_managers_alter_cliente_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='imagem',
        ),
    ]
