# Generated by Django 4.2.1 on 2023-05-19 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashbank', '0007_remove_cliente_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='fk_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='fk_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cartao', models.CharField(max_length=20)),
                ('cvv', models.IntegerField()),
                ('data_vencimento', models.DateField()),
                ('bandeira', models.CharField(max_length=20)),
                ('nome_titular_cartao', models.CharField(max_length=100)),
                ('cartao_ativo', models.BooleanField()),
                ('conta_cartao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cashbank.conta')),
            ],
            options={
                'verbose_name_plural': 'Cartao',
            },
        ),
        migrations.AddConstraint(
            model_name='cartao',
            constraint=models.UniqueConstraint(fields=('numero_cartao',), name='unique_numero_cartao'),
        ),
    ]
