# Generated by Django 4.2.1 on 2023-05-22 19:16

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashbank', '0008_alter_conta_fk_cliente_alter_endereco_fk_cliente_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cliente',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
