# Generated by Django 4.2.1 on 2023-05-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbank', '0013_remove_cliente_nome_cliente_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartao',
            old_name='conta_cartao',
            new_name='fk_conta_cartao',
        ),
        migrations.AlterField(
            model_name='cartao',
            name='cartao_ativo',
            field=models.BooleanField(default=True),
        ),
    ]
