# Generated by Django 4.2.1 on 2023-05-23 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashbank', '0014_rename_conta_cartao_cartao_fk_conta_cartao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='nome_titular',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartao',
            name='numero_conta',
            field=models.IntegerField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora', models.DateField(auto_now=True)),
                ('valor', models.DecimalField(decimal_places=8, max_digits=8)),
                ('operacao', models.CharField(choices=[('PI', 'PIX'), ('DC', 'DOC')], default='PI', max_length=2)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_enviadas', to=settings.AUTH_USER_MODEL)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_recebidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
